image: nchain/buildtools:build-sv-bionic

pipelines:
  branches:
    master:
      - step:
          script:
            - ./autogen.sh
            - ./configure
            - make -j4
            - make -j4 check
    develop:
      - step:
          script:
            - ./autogen.sh
            - ./configure
            - make -j4
            - make -j4 check
    feature/SV-238-C++17:
    - step:
        script:
        - ./autogen.sh
        - ./configure
        - make -j4
        - make -j4 check
  pull-requests:
    '**':
      - step:
          script:
            - ./autogen.sh
            - ./configure
            - make -j4
            - make -j4 check
